FROM golang:1.26-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /catchy ./cmd/catchy

FROM gcr.io/distroless/static-debian12

COPY --from=build /catchy /catchy
COPY --from=build /src/public/ /public/

ENTRYPOINT ["/catchy"]

CMD ["serve", "--migrate"]
